import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import { COMPANY_INTENTS, companyFromIntent, type CompanyIntent } from "@beinfi/sdk";
import type { GlobalFlags } from "../lib/client.js";
import { apiBase, infiClient, provisioningApiBase } from "../lib/client.js";
import { createClaimable, getClaimable, type ClaimableTenantCreateResponse, type ClaimRef } from "../lib/claim.js";
import { DEFAULT_COMPANY_FILES, loadCompanyConfig, lockPathFor, writeCompanyFile, writeLock } from "../lib/company-file.js";
import { readProjectEnv } from "../lib/dotenv.js";
import { runDoctor } from "./doctor.js";
import { fail, ok, printJson } from "../lib/output.js";

export type BootstrapFlags = GlobalFlags & {
  intent?: string;
  ref?: ClaimRef;
  email?: string;
  accountName?: string;
  cwd?: string;
  skipSync?: boolean;
};

export type BootstrapResult = {
  ok: boolean;
  intent: CompanyIntent;
  ref: ClaimRef;
  claimable: {
    id: string;
    claimUrl: string;
    tenantSlug: string;
    expiresAt: string;
    apiKeySecret: string;
    publishableKey?: string;
    accountName?: string;
    status?: string;
  };
  env: {
    INFI_SECRET_KEY: string;
    INFI_PUBLISHABLE_KEY?: string;
  };
  files: { env: string; company: string };
  /** Host the run actually talked to — inferred from the key, not hardcoded. */
  apiBase: string;
  sync: { actions: number; drift: number } | null;
  doctor: Awaited<ReturnType<typeof runDoctor>>;
  next: string[];
};

function isIntent(v: string): v is CompanyIntent {
  return (COMPANY_INTENTS as string[]).includes(v);
}

/** Minimal env — hosts inferred by SDK from key prefix (ADR 0004). */
function writeMinimalEnv(
  cwd: string,
  opts: { secretKey: string; publishableKey?: string; tenantSlug: string; claimId: string; claimUrl: string },
): string {
  const lines = [
    "# Generated by infi bootstrap — hosts are inferred from the key (sk_test_ / sk_live_)",
    `INFI_SECRET_KEY=${opts.secretKey}`,
    ...(opts.publishableKey ? [`INFI_PUBLISHABLE_KEY=${opts.publishableKey}`] : []),
    // Merchant slug for the hosted /pay/{slug} checkout.
    `INFI_TENANT_SLUG=${opts.tenantSlug}`,
    `INFI_CLAIM_ID=${opts.claimId}`,
    `INFI_CLAIM_URL=${opts.claimUrl}`,
  ];
  lines.push("");
  const file = path.join(cwd, ".env.local");
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  const owned = /^(?:export\s+)?INFI_(?:SECRET_KEY|PUBLISHABLE_KEY|TENANT_SLUG|CLAIM_ID|CLAIM_URL)=/;
  const preserved = existing.split("\n").filter((line) => !owned.test(line.trim()));
  fs.writeFileSync(file, [...preserved, ...lines].join("\n"), { mode: 0o600 });
  fs.chmodSync(file, 0o600);
  return file;
}

/** Programmatic bootstrap — used by CLI and MCP. */
export async function runBootstrap(flags: BootstrapFlags): Promise<BootstrapResult> {
  const cwd = path.resolve(flags.cwd ?? process.cwd());
  const stateDir = path.join(cwd, ".infi");
  const stateFile = path.join(stateDir, "bootstrap.json");
  type State = { intent: CompanyIntent; ref: ClaimRef; apiBase: string; claimable?: ClaimableTenantCreateResponse };
  const state: State | undefined = fs.existsSync(stateFile) ? JSON.parse(fs.readFileSync(stateFile, "utf8")) : undefined;
  const intentRaw = flags.intent ?? state?.intent ?? "crm";
  if (!isIntent(intentRaw)) throw new Error(`Unknown intent "${intentRaw}". Use one of: ${COMPANY_INTENTS.join(", ")}`);
  if (state && state.intent !== intentRaw) throw new Error("This project already has an intent. Edit infi.company.ts and run infi sync.");
  const intent = intentRaw;
  const ref = state?.ref ?? flags.ref ?? "cli";
  const base = provisioningApiBase(flags);
  if (state && state.apiBase !== base) throw new Error("This project was provisioned on another API host. Restore the original INFI_API_URL before resuming.");
  if (state && !state.claimable) throw new Error("Provisioning outcome is uncertain or another bootstrap is running. Do not create another tenant; recover the original result before retrying.");
  const projectKey = readProjectEnv(cwd).INFI_SECRET_KEY;
  const existingKey = flags.key ?? process.env.INFI_SECRET_KEY ?? projectKey;
  if ((existingKey && existingKey !== state?.claimable?.apiKeySecret) || (projectKey && projectKey !== state?.claimable?.apiKeySecret)) {
    throw new Error("Infi is already configured. Run infi doctor / infi sync with the existing account.");
  }
  let claimable = state?.claimable;
  if (claimable) {
    const current = await getClaimable(base, claimable.id);
    claimable = { ...claimable, status: current.status, tenantSlug: current.tenantSlug, expiresAt: current.expiresAt };
    if (current.status === "UNCLAIMED" && Date.parse(current.expiresAt) <= Date.now()) throw new Error("This account has expired. Open its claim URL to review the next step.");
  } else {
    fs.mkdirSync(stateDir, { recursive: true, mode: 0o700 });
    const ignore = path.join(cwd, ".gitignore");
    const previous = fs.existsSync(ignore) ? fs.readFileSync(ignore, "utf8") : "";
    fs.writeFileSync(ignore, previous + "\n# Local Infi credentials and resumable setup\n/.infi/\n/.env.local\n");
    // Exclusive creation prevents simultaneous agents from provisioning twice.
    // An ambiguous HTTP failure leaves this marker; never blindly repeat a POST.
    fs.writeFileSync(stateFile, JSON.stringify({ intent, ref, apiBase: base }), { flag: "wx", mode: 0o600 });
    try {
      claimable = await createClaimable(base, { ref, email: flags.email, accountName: flags.accountName });
    } catch (error) {
      // Validation/rate-limit refusals did not provision anything and can be corrected.
      const status = (error as { status?: number }).status;
      if (status && [400, 401, 403, 404, 422, 429].includes(status)) fs.rmSync(stateFile);
      throw error;
    }
    const temp = `${stateFile}.tmp`;
    fs.writeFileSync(temp, JSON.stringify({ intent, ref, apiBase: base, claimable }), { mode: 0o600 });
    fs.renameSync(temp, stateFile);
  }
  const envFile = writeMinimalEnv(cwd, {
    secretKey: claimable.apiKeySecret,
    publishableKey: claimable.publishableKey,
    tenantSlug: claimable.tenantSlug,
    claimId: claimable.id,
    claimUrl: claimable.claimUrl,
  });
  const existingCompany = DEFAULT_COMPANY_FILES.map((file) => path.join(cwd, file)).find((file) => fs.existsSync(file));
  const companyFile = existingCompany ?? writeCompanyFile(cwd, intent);

  let syncResult: BootstrapResult["sync"] = null;
  if (!flags.skipSync) {
    const infi = infiClient({ ...flags, key: claimable.apiKeySecret });
    // Build the config in memory instead of importing the .ts we just wrote:
    // in a plain `npm init` project Node reads .ts as CJS and the ESM file it
    // generates throws "Cannot use import statement outside a module".
    const sync = await infi.sync(existingCompany ? await loadCompanyConfig(companyFile) : companyFromIntent(intent));
    writeLock(lockPathFor(companyFile), sync.lock);
    syncResult = { actions: sync.actions.length, drift: sync.drift.length };
  }

  const doctor = await runDoctor({ ...flags, key: claimable.apiKeySecret, json: true });

  return {
    ok: doctor.ok,
    intent,
    ref,
    claimable: {
      id: claimable.id,
      claimUrl: claimable.claimUrl,
      tenantSlug: claimable.tenantSlug,
      expiresAt: claimable.expiresAt,
      apiKeySecret: claimable.apiKeySecret,
      publishableKey: claimable.publishableKey,
      accountName: claimable.accountName,
      status: claimable.status,
    },
    env: {
      INFI_SECRET_KEY: claimable.apiKeySecret,
      ...(claimable.publishableKey ? { INFI_PUBLISHABLE_KEY: claimable.publishableKey } : {}),
    },
    files: {
      env: path.relative(cwd, envFile),
      company: path.relative(cwd, companyFile),
    },
    apiBase: base,
    sync: syncResult,
    doctor,
    next: [
      // products.enroll, not customers.create: the enrollment id is what usage,
      // credit and subscription calls take. customers.create makes a tenant-level
      // customer whose id those calls reject with 422 unknown customer — the trap
      // the docs spend a callout on, and this line used to point straight at it.
      "Identify the payer from your own auth: infi.products.enroll(productId, { externalId }) — use the returned .id",
      "Use infi.wallet.forCustomer(externalId, { productKey }) for credits/meter",
      "When ready for real money: infi go-live --json (claim → connect provider → webhook)",
    ],
  };
}

/** Ask only for missing information. No account is created until answers arrive. */
export async function runAgentOnboarding(flags: BootstrapFlags) {
  const resuming = fs.existsSync(path.join(flags.cwd ?? process.cwd(), ".infi", "bootstrap.json"));
  const existingKey = flags.key ?? process.env.INFI_SECRET_KEY ?? readProjectEnv(flags.cwd).INFI_SECRET_KEY;
  if (!resuming && existingKey) return {
    status: "existing_integration" as const,
    env: { INFI_SECRET_KEY: existingKey },
    apiBase: apiBase({ ...flags, key: existingKey }),
    doctor: await runDoctor({ ...flags, key: existingKey }),
    next: "Use the existing Infi account and company file. Continue with doctor/sync; do not create another account or ask signup questions.",
  };
  const questions = [
    { field: "email", question: "Which email should we use for your Infi account?", value: flags.email },
    { field: "accountName", question: "What is the name of your business or app?", value: flags.accountName },
    { field: "intent", question: "What are you integrating?", value: flags.intent, options: COMPANY_INTENTS },
  ].filter((item) => !item.value?.trim()).map(({ value: _value, ...question }) => question);
  if (!resuming && questions.length) return {
    status: "requires_input" as const,
    missingFields: questions.map((question) => question.field),
    questions,
    next: "Ask the user only these missing questions, then call again with all answers and the same cwd. Reuse an existing Infi integration when present.",
  };
  const result = await runBootstrap(flags);
  return {
    status: result.ok ? "ready" as const : "needs_attention" as const,
    ...result,
    registration: {
      status: result.claimable.status === "CLAIMED" ? "complete" as const : "pending_claim" as const,
      claimUrl: result.claimable.claimUrl,
      expiresAt: result.claimable.expiresAt,
      next: "The human signs in at claimUrl to own this same account. Continue integrating in sandbox; production setup happens in Infi. Never request their password or verification code.",
    },
    next: [...result.next, "Store INFI_SECRET_KEY only in server secrets. Expose only the Infi publishable key to browser code that needs it.", "Run an application-level test before telling the user the integration is working. Doctor checks setup, not the app."],
  };
}

export async function bootstrapCommand(flags: BootstrapFlags): Promise<void> {
  let result: BootstrapResult;
  try {
    result = await runBootstrap(flags);
  } catch (err) {
    fail(err, flags.json);
  }

  if (flags.json) {
    printJson(result);
    if (!result.ok) process.exitCode = 1;
    return;
  }

  ok(`Bootstrapped company intent "${result.intent}"`);
  console.log(`  api:     ${result.apiBase}`);
  console.log(`  key:     ${result.claimable.apiKeySecret.slice(0, 12)}…`);
  console.log(`  company: ${result.files.company}`);
  console.log(`  env:     ${result.files.env}`);
  console.log(`  claim:   ${result.claimable.claimUrl}`);
  if (result.sync) console.log(`  sync:    ${result.sync.actions} actions`);
  console.log(pc.dim("\nHosts (API / app) are inferred from the key — no INFI_*_URL needed."));
  for (const step of result.next) console.log(pc.dim(`  → ${step}`));

  // The human path used to print success and exit 0 even when doctor failed.
  if (!result.ok) {
    console.error("");
    for (const check of result.doctor.checks.filter((c) => c.status === "fail")) {
      console.error(pc.red(`✗ ${check.message}`));
    }
    process.exitCode = 1;
  }
}
