import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import { COMPANY_INTENTS, type CompanyIntent } from "@beinfi/sdk";
import type { GlobalFlags } from "../lib/client.js";
import { apiBase, infiClient } from "../lib/client.js";
import { createClaimable, type ClaimRef } from "../lib/claim.js";
import {
  loadCompanyConfig,
  lockPathFor,
  writeCompanyFile,
  writeLock,
} from "../lib/company-file.js";
import { runDoctor } from "./doctor.js";
import { die, ok, printJson } from "../lib/output.js";

export type BootstrapFlags = GlobalFlags & {
  intent?: string;
  ref?: ClaimRef;
  slug?: string;
  cwd?: string;
  skipSync?: boolean;
};

export type BootstrapResult = {
  ok: boolean;
  intent: CompanyIntent;
  ref: ClaimRef;
  claimable: {
    id: string;
    claimUrl: string;
    tenantSlug: string;
    expiresAt: string;
    apiKeySecret: string;
  };
  env: {
    INFI_SECRET_KEY: string;
  };
  files: { env: string; company: string };
  sync: { actions: number; drift: number } | null;
  doctor: Awaited<ReturnType<typeof runDoctor>>;
  next: string[];
};

function isIntent(v: string): v is CompanyIntent {
  return (COMPANY_INTENTS as string[]).includes(v);
}

/** Minimal env — hosts inferred by SDK from key prefix (ADR 0004). */
function writeMinimalEnv(
  cwd: string,
  opts: { secretKey: string; tenantSlug: string; claimId: string; claimUrl: string },
): string {
  const lines = [
    "# Generated by infi bootstrap — hosts are inferred from the key (sk_test_ / sk_live_)",
    `INFI_SECRET_KEY=${opts.secretKey}`,
    // Merchant slug for the hosted /pay/{slug} checkout.
    `INFI_TENANT_SLUG=${opts.tenantSlug}`,
    `INFI_CLAIM_ID=${opts.claimId}`,
    `INFI_CLAIM_URL=${opts.claimUrl}`,
  ];
  lines.push("");
  const file = path.join(cwd, ".env.local");
  fs.writeFileSync(file, lines.join("\n"));
  return file;
}

/** Programmatic bootstrap — used by CLI and MCP. */
export async function runBootstrap(flags: BootstrapFlags): Promise<BootstrapResult> {
  const intentRaw = flags.intent ?? "crm";
  if (!isIntent(intentRaw)) {
    throw new Error(`Unknown intent "${intentRaw}". Use one of: ${COMPANY_INTENTS.join(", ")}`);
  }
  const intent = intentRaw;
  const cwd = flags.cwd ?? process.cwd();
  const ref = flags.ref ?? "cli";
  const base = apiBase(flags);

  const claimable = await createClaimable(base, { ref, intent });

  const envFile = writeMinimalEnv(cwd, {
    secretKey: claimable.apiKeySecret,
    tenantSlug: claimable.tenantSlug,
    claimId: claimable.id,
    claimUrl: claimable.claimUrl,
  });

  const companyFile = writeCompanyFile(cwd, intent);

  let syncResult: BootstrapResult["sync"] = null;
  if (!flags.skipSync) {
    const infi = infiClient({ ...flags, key: claimable.apiKeySecret });
    const config = await loadCompanyConfig(companyFile);
    const sync = await infi.sync(config);
    writeLock(lockPathFor(companyFile), sync.lock);
    syncResult = { actions: sync.actions.length, drift: sync.drift.length };
  }

  const doctor = await runDoctor({ ...flags, key: claimable.apiKeySecret, json: true });

  return {
    ok: doctor.ok,
    intent,
    ref,
    claimable: {
      id: claimable.id,
      claimUrl: claimable.claimUrl,
      tenantSlug: claimable.tenantSlug,
      expiresAt: claimable.expiresAt,
      apiKeySecret: claimable.apiKeySecret,
    },
    env: {
      INFI_SECRET_KEY: claimable.apiKeySecret,
    },
    files: {
      env: path.relative(cwd, envFile),
      company: path.relative(cwd, companyFile),
    },
    sync: syncResult,
    doctor,
    next: [
      "Identify the payer from your own auth: infi.customers.create({ externalId })",
      "Use infi.wallet.forCustomer(externalId, { productKey }) for credits/meter",
      "When ready for real money: infi go-live --json (claim → account → KYC)",
    ],
  };
}

export async function bootstrapCommand(flags: BootstrapFlags): Promise<void> {
  let result: BootstrapResult;
  try {
    result = await runBootstrap(flags);
  } catch (err) {
    die(err instanceof Error ? err.message : String(err));
  }

  if (flags.json) {
    printJson(result);
    if (!result.ok) process.exitCode = 1;
    return;
  }

  ok(`Bootstrapped company intent "${result.intent}"`);
  console.log(`  key:     ${result.claimable.apiKeySecret.slice(0, 12)}…`);
  console.log(`  company: ${result.files.company}`);
  console.log(`  env:     ${result.files.env}`);
  console.log(`  claim:   ${result.claimable.claimUrl}`);
  if (result.sync) console.log(`  sync:    ${result.sync.actions} actions`);
  console.log(pc.dim("\nHosts (API / auth / pay) are inferred from the key — no INFI_*_URL needed."));
  for (const step of result.next) console.log(pc.dim(`  → ${step}`));
}
