/**
 * @beinfi/sdk — AI Agent Billing Demo
 *
 * Company as code → real AI calls → usage invoice → (optional) webhooks → go-live hint.
 *
 * Usage:
 *   bun run start
 *   # or with an existing key:
 *   INFI_SECRET_KEY=sk_test_xxx OPENAI_API_KEY=sk-xxx GEMINI_API_KEY=xxx bun run start
 *
 * If INFI_SECRET_KEY is missing, the script claims a sandbox tenant automatically.
 * Optional: NGROK_AUTHTOKEN for live webhook waits.
 */
import { google } from "@ai-sdk/google";
import { openai } from "@ai-sdk/openai";
import ngrok from "@ngrok/ngrok";
import { generateText } from "ai";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  Infi,
  verifyWebhook,
  type PaymentConfirmedData,
  type WebhookEvent,
} from "@beinfi/sdk";
import { createClaimable } from "@beinfi/cli/claim";
import { runDoctor } from "@beinfi/cli/doctor";
import { getGoLiveStatus } from "@beinfi/cli/go-live";
import company, { PRODUCT_KEY, CURRENCY } from "./infi.company.js";

const ROOT = path.dirname(fileURLToPath(import.meta.url));

// The Vercel AI SDK's Google provider reads GOOGLE_GENERATIVE_AI_API_KEY;
// accept GEMINI_API_KEY as a friendlier alias.
if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY && process.env.GEMINI_API_KEY) {
  process.env.GOOGLE_GENERATIVE_AI_API_KEY = process.env.GEMINI_API_KEY;
}

const WEBHOOK_PORT = parseInt(process.env.WEBHOOK_PORT || "9876", 10);
const CUSTOMER_EMAIL = process.env.CUSTOMER_EMAIL || "demo@example.com";
const CLAIM_API =
  process.env.INFI_API_URL?.replace(/\/$/, "") ?? "https://api-sandbox.beinfi.com";

function header(text: string) {
  console.log(`\n${"=".repeat(50)}`);
  console.log(`  ${text}`);
  console.log("=".repeat(50));
}

/** Claim a sandbox tenant when no key is set (bootstrap lite — keeps our infi.company.ts). */
async function ensureSecretKey(): Promise<{ key: string; claimUrl?: string; claimId?: string }> {
  const existing = process.env.INFI_SECRET_KEY;
  if (existing?.startsWith("sk_")) {
    return {
      key: existing,
      claimUrl: process.env.INFI_CLAIM_URL,
      claimId: process.env.INFI_CLAIM_ID,
    };
  }

  header("0. Bootstrap — claim sandbox tenant");
  console.log("No INFI_SECRET_KEY — provisioning claimable tenant (ref=cli)…");
  console.log(pcDim(`(CLI equivalent: infi bootstrap --intent usage-saas --json)`));

  const claimable = await createClaimable(CLAIM_API, {
    ref: "cli",
    intent: "usage-saas",
  });
  process.env.INFI_SECRET_KEY = claimable.apiKeySecret;
  process.env.INFI_CLAIM_ID = claimable.id;
  process.env.INFI_CLAIM_URL = claimable.claimUrl;

  const envPath = path.join(ROOT, ".env.local");
  fs.writeFileSync(
    envPath,
    [
      "# Generated by ai-agent-billing demo — hosts inferred from key",
      `INFI_SECRET_KEY=${claimable.apiKeySecret}`,
      `INFI_CLAIM_ID=${claimable.id}`,
      `INFI_CLAIM_URL=${claimable.claimUrl}`,
      "",
    ].join("\n"),
  );

  console.log(`  key:   ${claimable.apiKeySecret.slice(0, 14)}…`);
  console.log(`  claim: ${claimable.claimUrl}`);
  console.log(`  env:   ${path.relative(ROOT, envPath)}`);

  return {
    key: claimable.apiKeySecret,
    claimUrl: claimable.claimUrl,
    claimId: claimable.id,
  };
}

function pcDim(s: string): string {
  return `\x1b[2m${s}\x1b[0m`;
}

function startWebhookServer(secret: string, port: number) {
  const listeners = new Map<string, (event: WebhookEvent) => void>();

  const server = Bun.serve({
    port,
    async fetch(req) {
      if (req.method !== "POST") return new Response("OK", { status: 200 });

      const rawBody = await req.text();
      let event: WebhookEvent;
      try {
        event = verifyWebhook(
          {
            id: req.headers.get("x-webhook-id") || "",
            timestamp: req.headers.get("x-webhook-timestamp") || "",
            signature: req.headers.get("x-webhook-signature") || "",
            eventType: req.headers.get("x-webhook-event-type") || "",
            body: rawBody,
          },
          secret,
        );
      } catch {
        return new Response("Invalid signature", { status: 401 });
      }

      listeners.get(event.type)?.(event);
      return new Response("OK", { status: 200 });
    },
  });

  return {
    server,
    waitForEvent(eventType: string, timeoutMs = 30_000): Promise<WebhookEvent> {
      return new Promise((resolve, reject) => {
        const timer = setTimeout(() => {
          listeners.delete(eventType);
          reject(new Error(`Timeout waiting for ${eventType}`));
        }, timeoutMs);

        listeners.set(eventType, (event) => {
          clearTimeout(timer);
          listeners.delete(eventType);
          resolve(event);
        });
      });
    },
  };
}

let cleanedUp = false;
let activeTunnel: ngrok.Listener | null = null;
let webhookServer: { stop: () => void } | null = null;
let webhookId: string | undefined;
let infi: Infi;

async function cleanup() {
  if (cleanedUp) return;
  cleanedUp = true;
  console.log("\nCleaning up...");
  try {
    if (webhookId && infi) await infi.webhooks.delete(webhookId);
  } catch {
    // best-effort
  }
  webhookServer?.stop();
  if (activeTunnel) {
    await ngrok.disconnect();
    console.log("Tunnel closed");
  }
}

async function main() {
  const { key, claimId } = await ensureSecretKey();

  infi = new Infi({
    secretKey: key,
    ...(process.env.INFI_API_URL ? { apiUrl: process.env.INFI_API_URL } : {}),
  });

  // ── A. Company sync ─────────────────────────────────────────────────────
  header("1. Sync company (infi.company.ts)");

  const sync = await infi.sync(company);
  console.log(
    `Synced (${sync.actions.length} actions):`,
    sync.actions.map((a) => `${a.action}:${a.resource}`).join(", ") || "none",
  );

  header("1b. Doctor");
  const doctor = await runDoctor({
    key,
    local: Boolean(process.env.INFI_API_URL?.includes("localhost")),
    json: true,
  });
  for (const check of doctor.checks) {
    const mark = check.status === "pass" ? "✓" : check.status === "warn" ? "!" : "✗";
    console.log(`  ${mark} ${check.message}`);
    if (check.fix?.command) console.log(pcDim(`    fix: ${check.fix.command}`));
  }
  if (!doctor.ok) {
    throw new Error("infi doctor failed — fix the checks above and re-run.");
  }

  const product = (await infi.products.list()).find((p) => p.key === PRODUCT_KEY);
  if (!product?.id) throw new Error(`Product ${PRODUCT_KEY} not found after sync`);
  console.log(`Product: ${product.id} (${product.name})`);

  // ── B. Customer ─────────────────────────────────────────────────────────
  header("2. Register Customer");

  const enrollment = await infi.products.enroll(product.id, {
    externalId: "customer_001",
    name: "Acme Corp",
    email: CUSTOMER_EMAIL,
  });
  const customerId = enrollment.id!;
  console.log(`Customer registered: ${enrollment.externalId} (${enrollment.name})`);
  console.log(`Invoice will be sent to: ${CUSTOMER_EMAIL}`);

  // ── C. Webhooks (optional) ──────────────────────────────────────────────
  header("3. Start Webhook Listener");

  let waitForEvent: ((type: string, ms?: number) => Promise<WebhookEvent>) | null = null;
  if (process.env.NGROK_AUTHTOKEN) {
    const listener = await ngrok.forward({ addr: WEBHOOK_PORT, authtoken_from_env: true });
    const tunnelUrl = listener.url()!;
    activeTunnel = listener;
    console.log(`Tunnel open: ${tunnelUrl} -> localhost:${WEBHOOK_PORT}`);

    const webhook = await infi.webhooks.create({
      url: tunnelUrl,
      events: ["invoice.finalized", "invoice.sent", "payment.confirmed", "payment.failed"],
    });
    webhookId = webhook.id;
    if (!webhook.secret) throw new Error("webhook endpoint returned no signing secret");
    console.log(`Webhook registered: ${webhook.id}`);

    const started = startWebhookServer(webhook.secret, WEBHOOK_PORT);
    webhookServer = started.server;
    waitForEvent = started.waitForEvent;
    console.log(`Webhook server listening on port ${WEBHOOK_PORT}`);
  } else {
    console.log("NGROK_AUTHTOKEN not set — skipping webhooks (billing flow still runs).");
  }

  // ── D. AI + metering ────────────────────────────────────────────────────
  header("4. AI Agent Usage");
  const windowStart = new Date().toISOString();
  let totalTokens = 0;
  let billedCalls = 0;

  // One call via infi.meter (postpaid = record, no credit gate) — auto-extracts AI SDK tokens.
  console.log(`\n  -> [meter/postpaid] gpt-4o-mini "What is usage-based billing in one sentence?"`);
  try {
    const metered = await infi.meter(
      {
        enrollmentId: customerId,
        productId: product.id,
        meter: "tokens",
        mode: "postpaid",
        metadata: { model: "gpt-4o-mini", via: "infi.meter" },
      },
      () =>
        generateText({
          model: openai("gpt-4o-mini"),
          prompt: "What is usage-based billing in one sentence?",
        }),
    );
    const tokens = metered.usage.totalTokens ?? 0;
    totalTokens += tokens;
    billedCalls += 1;
    // Also count the request meter for this turn
    await infi.track({
      customerId,
      productId: product.id,
      meter: "requests",
      value: "1",
      metadata: { model: "gpt-4o-mini", via: "infi.meter" },
    });
    console.log(
      `     Response (${tokens} tokens): ${metered.text.slice(0, 120).replace(/\n/g, " ")}...`,
    );
    console.log(pcDim("     recorded via infi.meter({ mode: \"postpaid\" })"));
  } catch (err) {
    console.log(
      `     skipped (meter): ${err instanceof Error ? err.message.split("\n")[0] : err}`,
    );
  }

  // Remaining calls via session batch (tokens + requests per turn).
  const prompts = [
    {
      prompt: "Summarize the benefits of serverless architecture in 2 sentences.",
      model: openai("gpt-4o-mini"),
      label: "gpt-4o-mini",
    },
    {
      prompt: "Write a one-paragraph marketing copy for a fintech API platform.",
      model: google("gemini-2.0-flash"),
      label: "gemini-2.0-flash",
    },
    {
      prompt: 'Translate to Portuguese: "Usage-based billing lets you pay only for what you use."',
      model: openai("gpt-4o-mini"),
      label: "gpt-4o-mini",
    },
    {
      prompt: "Explain the difference between REST and GraphQL in 3 bullet points.",
      model: google("gemini-2.0-flash"),
      label: "gemini-2.0-flash",
    },
  ];

  const session = infi.session(customerId, product.id);

  for (const { prompt, model, label } of prompts) {
    console.log(`\n  -> [session] [${label}] "${prompt}"`);
    let result;
    try {
      result = await generateText({ model, prompt });
    } catch (err) {
      console.log(
        `     skipped (${label}): ${err instanceof Error ? err.message.split("\n")[0] : err}`,
      );
      continue;
    }
    const tokens = result.usage.totalTokens ?? 0;
    totalTokens += tokens;
    billedCalls += 1;
    console.log(
      `     Response (${tokens} tokens): ${result.text.slice(0, 120).replace(/\n/g, " ")}...`,
    );
    session.track("tokens", tokens, { model: label });
    session.track("requests", 1, { model: label });
  }

  const eventCount = session.size;
  await session.flush();
  console.log(`\nSession batch sent: ${eventCount} events`);
  console.log(`Total tokens used: ${totalTokens} across ${billedCalls} calls`);

  // ── E. Usage + invoice ──────────────────────────────────────────────────
  header("5. Check Usage");

  const usage = await infi.usage.get({
    customerId,
    from: windowStart,
    to: new Date().toISOString(),
  });
  let totalCost = 0;
  for (const m of usage.meters) {
    const amount = Number(m.totalAmount ?? 0);
    totalCost += amount;
    console.log(`  ${m.meter}: ${m.totalValue} ${m.unit}s = ${CURRENCY} ${amount.toFixed(2)}`);
  }
  console.log(`\n  Total: ${CURRENCY} ${totalCost.toFixed(2)}`);

  header("6. Generate Invoice");
  const to = new Date().toISOString();
  console.log(`Period: ${windowStart.split("T")[0]} to ${to.split("T")[0]}`);

  const invoice = await infi.invoices.fromUsage({
    customerId,
    from: windowStart,
    to,
  });
  console.log(`Invoice created: ${invoice.invoiceNumber ?? invoice.id}`);
  console.log(`  Status: ${invoice.status}`);
  console.log(`  Total: ${invoice.currency} ${invoice.total}`);

  header("7. Wait for invoice.finalized Webhook");
  if (waitForEvent) {
    try {
      const event = await waitForEvent("invoice.finalized", 30_000);
      console.log("Webhook received! Payload:");
      console.log(JSON.stringify(event.data, null, 2));
    } catch {
      console.log("Timeout: invoice.finalized webhook not received within 30s (continuing anyway)");
    }
  } else {
    console.log("(webhooks disabled)");
  }

  header("8. Send Invoice Email");
  await infi.invoices.send(invoice.id!);
  console.log(`Invoice email sent to ${CUSTOMER_EMAIL} (hosted pay link included)`);

  header("9. Wait for payment.confirmed Webhook");
  if (waitForEvent) {
    console.log("Waiting for customer to pay the invoice...");
    try {
      const event = await waitForEvent("payment.confirmed", 300_000);
      const data = event.data as PaymentConfirmedData;
      console.log(
        `Payment confirmed! ${data.amount} ${data.currency} (payment ${data.paymentId})`,
      );
    } catch {
      console.log("Timeout: payment.confirmed webhook not received within 5min (continuing anyway)");
    }
  } else {
    console.log("(webhooks disabled — customer pays via the emailed link)");
  }

  header("10. Cleanup");
  if (webhookId) {
    await infi.webhooks.delete(webhookId);
    console.log(`Webhook deleted: ${webhookId}`);
  }
  webhookServer?.stop();
  if (activeTunnel) {
    await ngrok.disconnect();
    console.log("Tunnel closed");
  }

  // ── F. Go-live hint ─────────────────────────────────────────────────────
  header("11. Go-live (sandbox → real money)");
  const goLive = await getGoLiveStatus({
    key,
    claimId: claimId ?? process.env.INFI_CLAIM_ID,
    local: Boolean(process.env.INFI_API_URL?.includes("localhost")),
    json: true,
  });
  console.log(`  stage: ${goLive.stage}`);
  console.log(`  next:  ${goLive.next}`);
  if (goLive.urls.claim) console.log(`  claim: ${goLive.urls.claim}`);
  if (goLive.urls.kyc) console.log(`  kyc:   ${goLive.urls.kyc}`);
  console.log(pcDim("  CLI: infi go-live --json"));

  header("Done!");
  console.log(`
Summary:
  Product:    ${product.name} (${product.id})
  Customer:   ${enrollment.name} <${CUSTOMER_EMAIL}>
  Usage:      ${billedCalls} AI calls (${totalTokens} tokens)
  Invoice:    ${invoice.invoiceNumber ?? invoice.id} — ${invoice.currency} ${invoice.total}
  Webhooks:   ${waitForEvent ? "received & cleaned up" : "disabled (no NGROK_AUTHTOKEN)"}
  Go-live:    ${goLive.stage}
`);
}

process.on("SIGINT", async () => {
  await cleanup();
  process.exit(0);
});

main().catch(async (err) => {
  console.error("Script failed:", err);
  await cleanup();
  process.exit(1);
});
