import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { BillingConfig, CompanyIntent, SyncLock } from "@beinfi/sdk";
import { die } from "./output.js";

export const DEFAULT_COMPANY_FILES = [
  "infi.company.ts",
  "infi.company.mts",
  "infi.billing.ts",
  "infi.billing.mts",
  "billing.config.ts",
];

export function lockFileNameFor(configFile: string): string {
  const base = path.basename(configFile);
  if (base.startsWith("infi.company")) return "infi.company.lock.json";
  return "infi.billing.lock.json";
}

export function lockPathFor(configFile: string): string {
  return path.join(path.dirname(path.resolve(configFile)), lockFileNameFor(configFile));
}

export async function loadCompanyConfig(filePath: string): Promise<BillingConfig> {
  const abs = path.resolve(filePath);
  if (!fs.existsSync(abs)) die(`Company config not found: ${abs}`);

  const mod = (await import(pathToFileURL(abs).href)) as {
    default?: BillingConfig;
    billing?: BillingConfig;
    company?: BillingConfig;
  };

  const config = mod.default ?? mod.company ?? mod.billing;
  if (!config?.products?.length) {
    die(
      `No company config exported from ${abs} (expected default export from defineCompany(...) or defineBilling(...))`,
    );
  }
  return config;
}

export function resolveCompanyFile(explicit?: string): string {
  if (explicit) return explicit;
  for (const candidate of DEFAULT_COMPANY_FILES) {
    if (fs.existsSync(path.resolve(candidate))) return candidate;
  }
  die(`No company config found. Pass a file or create infi.company.ts`);
}

export function readLock(lockPath: string): SyncLock | undefined {
  if (!fs.existsSync(lockPath)) return undefined;
  try {
    return JSON.parse(fs.readFileSync(lockPath, "utf8")) as SyncLock;
  } catch {
    return undefined;
  }
}

export function writeLock(lockPath: string, lock: SyncLock): void {
  fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

/** Generate infi.company.ts from an intent. */
export function renderCompanyFile(intent: CompanyIntent): string {
  const lines = [
    `import { defineCompany } from "@beinfi/sdk";`,
    ``,
    `/** Company as code — generated by \`infi bootstrap --intent ${intent}\`. */`,
    `export default defineCompany.fromIntent(${JSON.stringify(intent)});`,
    ``,
  ];
  return lines.join("\n");
}

export function writeCompanyFile(cwd: string, intent: CompanyIntent): string {
  const file = path.join(cwd, "infi.company.ts");
  fs.writeFileSync(file, renderCompanyFile(intent));
  return file;
}
