import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { readProjectEnv } from "./dotenv.js";

const temps: string[] = [];
function tmp(files: Record<string, string>): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), "infi-env-"));
  temps.push(d);
  for (const [name, body] of Object.entries(files)) fs.writeFileSync(path.join(d, name), body);
  return d;
}
afterEach(() => {
  for (const d of temps.splice(0)) fs.rmSync(d, { recursive: true, force: true });
});

describe("readProjectEnv", () => {
  // The exact file `bootstrap` writes. Not reading it back is what made `infi sync`
  // fail with missing_secret_key seconds after bootstrap succeeded.
  it("reads the file bootstrap generates", () => {
    const dir = tmp({
      ".env.local": [
        "# Auto-generated by infi init",
        'DATABASE_URL="postgresql://app:app@localhost:5432/app"',
        "",
        "INFI_SECRET_KEY=sk_test_abc123",
        "INFI_TENANT_SLUG=app-7f3",
        "APP_URL=http://localhost:3000",
      ].join("\n"),
    });

    expect(readProjectEnv(dir)).toEqual({
      INFI_SECRET_KEY: "sk_test_abc123",
      INFI_TENANT_SLUG: "app-7f3",
    });
  });

  it("honours the local API override init writes", () => {
    const dir = tmp({ ".env.local": "INFI_SECRET_KEY=sk_test_x\nINFI_API_URL=http://localhost:8088\n" });
    expect(readProjectEnv(dir).INFI_API_URL).toBe("http://localhost:8088");
  });

  it("strips quotes and ignores comments and blanks", () => {
    const dir = tmp({ ".env": '\n# comment\nINFI_SECRET_KEY="sk_test_q"\n\nNOT_OURS=1\n' });
    expect(readProjectEnv(dir)).toEqual({ INFI_SECRET_KEY: "sk_test_q" });
  });

  // Merging two files is how you end up with a key from one and a host from the
  // other, pointed at different environments.
  it("takes .env.local whole and does not merge .env into it", () => {
    const dir = tmp({
      ".env.local": "INFI_SECRET_KEY=sk_test_local\n",
      ".env": "INFI_SECRET_KEY=sk_live_other\nINFI_API_URL=https://api.beinfi.com\n",
    });

    expect(readProjectEnv(dir)).toEqual({ INFI_SECRET_KEY: "sk_test_local" });
  });

  it("is empty, not an error, when there is no file", () => {
    expect(readProjectEnv(tmp({}))).toEqual({});
  });

  it("ignores an empty assignment rather than returning a blank key", () => {
    const dir = tmp({ ".env.local": "INFI_SECRET_KEY=\n" });
    expect(readProjectEnv(dir)).toEqual({});
  });
});
