import fs from "node:fs";
import path from "node:path";
import type { ClaimableTenantCreateResponse } from "./claim.js";

export type TemplateId = "default" | "crm" | "ebook-sale" | "ai-chat" | "marketplace-billing";

export type TemplateMeta = { label: string; hint: string };

export const TEMPLATE_META: Record<TemplateId, TemplateMeta> = {
  default: { label: "Default", hint: "Next.js fullstack — auth + checkout + dashboard" },
  crm: { label: "CRM", hint: "contacts, pipeline, usage metering" },
  "ebook-sale": { label: "Ebook sale", hint: "one-time checkout, no login" },
  "ai-chat": { label: "AI chat", hint: "Vite + Hono, prepaid credits" },
  "marketplace-billing": { label: "Marketplace billing", hint: "per-org usage billing" },
};

export const DEFAULT_PORT = 3000;

export function slugFromName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "my-app"
  );
}

export function validateProjectName(name: string): string | undefined {
  if (!name.trim()) return "Project name is required";
  if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
    return "Use letters, numbers, dots, dashes, and underscores only";
  }
  return undefined;
}

export type EnvOptions = {
  targetDir: string;
  appSlug: string;
  appName: string;
  port: number;
  local: boolean;
};

const PROD = {
  api: "https://api.beinfi.com",
  frontend: "https://app.beinfi.com",
};

const LOCAL = {
  api: "http://localhost:8088",
  frontend: "http://localhost:4003",
};

export function writeEnvFile(options: EnvOptions, claimable: ClaimableTenantCreateResponse): void {
  const bases = options.local ? LOCAL : PROD;
  const origin = `http://localhost:${options.port}`;
  const dbUrl = "postgresql://app:app@localhost:5432/app";

  const lines = [
    "# Auto-generated by infi init",
    `DATABASE_URL="${dbUrl}"`,
    "",
    `INFI_SECRET_KEY=${claimable.apiKeySecret}`,
    `INFI_API_URL=${bases.api}`,
    `NEXT_PUBLIC_INFI_API_URL=${bases.api}`,
    `NEXT_PUBLIC_INFI_AUTH_BASE_URL=${bases.frontend}`,
    `INFI_PAY_BASE_URL=${bases.frontend}`,
    `NEXT_PUBLIC_INFI_APP_SLUG=${claimable.appSlug || options.appSlug}`,
    `INFI_CLAIM_ID=${claimable.id}`,
    `INFI_CLAIM_URL=${claimable.claimUrl}`,
    "",
    `NEXT_PUBLIC_APP_NAME=${options.appName}`,
    `NEXT_PUBLIC_APP_ORIGIN=${origin}`,
    "",
  ];

  fs.writeFileSync(path.join(options.targetDir, ".env.local"), `${lines.join("\n")}\n`);
}

export function writeEnvExample(targetDir: string, appName: string, appSlug: string, port: number): void {
  const example = `# PostgreSQL
DATABASE_URL="postgresql://app:app@localhost:5432/app"

INFI_SECRET_KEY=sk_test_replace_me
INFI_API_URL=https://api.beinfi.com
NEXT_PUBLIC_INFI_API_URL=https://api.beinfi.com
NEXT_PUBLIC_INFI_AUTH_BASE_URL=https://app.beinfi.com
INFI_PAY_BASE_URL=https://app.beinfi.com
NEXT_PUBLIC_INFI_APP_SLUG=${appSlug}
INFI_CLAIM_ID=
INFI_CLAIM_URL=

NEXT_PUBLIC_APP_NAME=${appName}
NEXT_PUBLIC_APP_ORIGIN=http://localhost:${port}
`;
  fs.writeFileSync(path.join(targetDir, ".env.example"), example);
}
