import fs from "node:fs";
import path from "node:path";
import type { ClaimableTenantCreateResponse } from "./claim.js";

export type TemplateId = "default" | "crm" | "ebook-sale" | "ai-chat" | "marketplace-billing";

export type TemplateMeta = { label: string; hint: string };

export const TEMPLATE_META: Record<TemplateId, TemplateMeta> = {
  default: { label: "Default", hint: "Next.js fullstack — auth + checkout + dashboard" },
  crm: { label: "CRM", hint: "contacts, pipeline, usage metering" },
  "ebook-sale": { label: "Ebook sale", hint: "one-time checkout, no login" },
  "ai-chat": { label: "AI chat", hint: "Vite + Hono, prepaid credits" },
  "marketplace-billing": { label: "Marketplace billing", hint: "per-org usage billing" },
};

export const DEFAULT_PORT = 3000;

export function slugFromName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "my-app"
  );
}

export function validateProjectName(name: string): string | undefined {
  if (!name.trim()) return "Project name is required";
  if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
    return "Use letters, numbers, dots, dashes, and underscores only";
  }
  return undefined;
}

export type EnvOptions = {
  targetDir: string;
  appSlug: string;
  appName: string;
  port: number;
  local: boolean;
};

/**
 * Minimal env — API/auth/pay hosts are inferred by the SDK from the key prefix.
 * Only set INFI_API_URL when --local (override).
 */
export function writeEnvFile(options: EnvOptions, claimable: ClaimableTenantCreateResponse): void {
  const origin = `http://localhost:${options.port}`;
  const dbUrl = "postgresql://app:app@localhost:5432/app";

  const lines = [
    "# Auto-generated by infi init — hosts inferred from INFI_SECRET_KEY (sk_test_/sk_live_)",
    `DATABASE_URL="${dbUrl}"`,
    "",
    `INFI_SECRET_KEY=${claimable.apiKeySecret}`,
    `INFI_TENANT_SLUG=${claimable.tenantSlug}`,
    `INFI_CLAIM_ID=${claimable.id}`,
    `INFI_CLAIM_URL=${claimable.claimUrl}`,
    `APP_URL=${origin}`,
    `NEXT_PUBLIC_APP_NAME=${options.appName}`,
    `NEXT_PUBLIC_APP_ORIGIN=${origin}`,
  ];

  if (options.local) {
    lines.push("", "# Local overrides (optional — omit in Lovable/prod)", "INFI_API_URL=http://localhost:8088");
  }

  lines.push("");
  fs.writeFileSync(path.join(options.targetDir, ".env.local"), `${lines.join("\n")}\n`);
}

export function writeEnvExample(targetDir: string, appName: string, port: number): void {
  const example = `# PostgreSQL
DATABASE_URL="postgresql://app:app@localhost:5432/app"

# Required — hosts (API / auth / pay) are inferred from the key prefix
INFI_SECRET_KEY=sk_test_replace_me
INFI_CLAIM_ID=
INFI_CLAIM_URL=
APP_URL=http://localhost:${port}

NEXT_PUBLIC_APP_NAME=${appName}
NEXT_PUBLIC_APP_ORIGIN=http://localhost:${port}

# Optional local override only:
# INFI_API_URL=http://localhost:8088
`;
  fs.writeFileSync(path.join(targetDir, ".env.example"), example);
}
