import fs from "node:fs";
import path from "node:path";
import { Infi } from "@beinfi/sdk";
import type { ClaimableSandboxCreateResponse } from "@beinfi/sdk";

export type ProvisionOptions = {
  targetDir: string;
  appSlug: string;
  appName: string;
  port: number;
  local: boolean;
};

const PROD = {
  api: "https://api.beinfi.com",
  frontend: "https://app.beinfi.com",
};

const LOCAL = {
  api: "http://localhost:8088",
  frontend: "http://localhost:4003",
};

export async function provisionSandbox(local: boolean): Promise<ClaimableSandboxCreateResponse> {
  const baseUrl = local ? LOCAL.api : PROD.api;
  const infi = new Infi({ baseUrl });
  return infi.sandbox.create({ ref: "cli", baseUrl });
}

export function writeEnvFile(options: ProvisionOptions, sandbox: ClaimableSandboxCreateResponse): void {
  const bases = options.local ? LOCAL : PROD;
  const origin = `http://localhost:${options.port}`;
  const dbUrl = "postgresql://app:app@localhost:5432/app";

  const lines = [
    "# Auto-generated by create-beinfi-app",
    `DATABASE_URL="${dbUrl}"`,
    "",
    `INFI_SECRET_KEY=${sandbox.apiKeySecret}`,
    `INFI_API_URL=${bases.api}`,
    `NEXT_PUBLIC_INFI_AUTH_BASE_URL=${bases.frontend}`,
    `INFI_PAY_BASE_URL=${bases.frontend}`,
    `NEXT_PUBLIC_INFI_APP_SLUG=${sandbox.appSlug || options.appSlug}`,
    `INFI_SANDBOX_ID=${sandbox.id}`,
    `INFI_SANDBOX_CLAIM_URL=${sandbox.claimUrl}`,
    "",
    `NEXT_PUBLIC_APP_NAME=${options.appName}`,
    `NEXT_PUBLIC_APP_ORIGIN=${origin}`,
    "",
  ];

  fs.writeFileSync(path.join(options.targetDir, ".env.local"), `${lines.join("\n")}\n`);
}

export function writeEnvExample(targetDir: string, appName: string, appSlug: string, port: number): void {
  const example = `# PostgreSQL
DATABASE_URL="postgresql://app:app@localhost:5432/app"

INFI_SECRET_KEY=sk_test_replace_me
INFI_API_URL=https://api.beinfi.com
NEXT_PUBLIC_INFI_AUTH_BASE_URL=https://app.beinfi.com
INFI_PAY_BASE_URL=https://app.beinfi.com
NEXT_PUBLIC_INFI_APP_SLUG=${appSlug}
INFI_SANDBOX_ID=
INFI_SANDBOX_CLAIM_URL=

NEXT_PUBLIC_APP_NAME=${appName}
NEXT_PUBLIC_APP_ORIGIN=http://localhost:${port}
`;
  fs.writeFileSync(path.join(targetDir, ".env.example"), example);
}
